DROP TABLE DBM_SANDBOX..PI_TABMODEL_BOOSTED IF EXISTS;

CREATE TABLE DBM_SANDBOX..PI_TABMODEL_BOOSTED( 
     LAST_NAME CHARACTER VARYING(30),
     ADDRESS_LINE_1 CHARACTER VARYING(30),
     ADDRESS_LINE_2 CHARACTER VARYING(30),
     STATE_CODE CHARACTER VARYING(19),
     ZIP CHARACTER VARYING(5),
     LOG_SCORE DOUBLE)
     DISTRIBUTE ON (LAST_NAME, ADDRESS_LINE_1, STATE_CODE, ZIP);


INSERT INTO DBM_SANDBOX..PI_TABMODEL_BOOSTED
     SELECT * FROM 
     EXTERNAL 'C:\Temp\tmpaxkblw4g\Scored.csv' 
     USING (
      DELIMITER ','
      Y2BASE 2000
      ENCODING 'internal'
      REMOTESOURCE 'ODBC'
      ESCAPECHAR ''
      MAXERRORS 0
); 
