SELECT DT.DATE_VALUE,
	   CONSENT.UMCSENT,
	   ST.STORE_NUMBER,
	   PD.SKU_DISPLAY_NUMBER,
	   MAX(CASE WHEN DT.CALENDAR_QUARTER = 1 THEN 1 ELSE 0 END) AS Q1, 
	   MAX(CASE WHEN DT.CALENDAR_QUARTER = 2 THEN 1 ELSE 0 END) AS Q2,
	   MAX(CASE WHEN DT.CALENDAR_QUARTER = 3 THEN 1 ELSE 0 END) AS Q3,
	   MAX(CASE WHEN DT.CALENDAR_QUARTER = 4 THEN 1 ELSE 0 END) AS Q4,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 1 THEN 1 ELSE 0 END) AS P1,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 2 THEN 1 ELSE 0 END) AS P2,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 3 THEN 1 ELSE 0 END) AS P3,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 4 THEN 1 ELSE 0 END) AS P4,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 5 THEN 1 ELSE 0 END) AS P5,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 6 THEN 1 ELSE 0 END) AS P6,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 7 THEN 1 ELSE 0 END) AS P7, 
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 8 THEN 1 ELSE 0 END) AS P8,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 9 THEN 1 ELSE 0 END) AS P9,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 10 THEN 1 ELSE 0 END) AS P10,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 11 THEN 1 ELSE 0 END) AS P11,
	   MAX(CASE WHEN DT.MONTH_NUMBER_IN_CALENDAR_YEAR = 12 THEN 1 ELSE 0 END) AS P12,
	   MAX(CASE WHEN DT.DAY_NUMBER_IN_WEEK = 1 THEN 1 ELSE 0 END) AS D1,
	   MAX(CASE WHEN DT.DAY_NUMBER_IN_WEEK = 2 THEN 1 ELSE 0 END) AS D2,
	   MAX(CASE WHEN DT.DAY_NUMBER_IN_WEEK = 3 THEN 1 ELSE 0 END) AS D3,
	   MAX(CASE WHEN DT.DAY_NUMBER_IN_WEEK = 4 THEN 1 ELSE 0 END) AS D4,
	   MAX(CASE WHEN DT.DAY_NUMBER_IN_WEEK = 5 THEN 1 ELSE 0 END) AS D5,
	   MAX(CASE WHEN DT.DAY_NUMBER_IN_WEEK = 6 THEN 1 ELSE 0 END) AS D6,
	   MAX(CASE WHEN DT.DAY_NUMBER_IN_WEEK = 7 THEN 1 ELSE 0 END) AS D7,
	   MAX(CURRENT_DATE - PD.SKU_DATE_CREATED) AS SKU_AGE,
	   MAX(CASE WHEN EVENT.PRODUCT_MEMBER_KEY IS NOT NULL THEN 1 ELSE 0 END) AS EVENT_SKU,
	   SUM(SD.INV_QUANTITY) AS TARGET_UNITS
FROM EDW_SPOKE..DIM_DATE DT
	LEFT JOIN EDW_SPOKE..FACT_BPS_SALES_HEADER SH ON DT.DATE_KEY = SH.TRANSACTION_DATE_KEY
	LEFT JOIN EDW_SPOKE..FACT_BPS_SALES_DETAIL SD ON SH.INBOUND_INTERACTION_KEY = SD.SH_INBOUND_INTERACTION_KEY
	LEFT JOIN EDW_SPOKE..DIM_STORE ST ON SD.STORE_MEMBER_KEY = ST.MEMBER_KEY
	
	LEFT JOIN EDW_SPOKE..DIM_PRODUCT_BPS PD ON SD.INVENTORY_PRODUCT_MEMBER_KEY = PD.MEMBER_KEY
	LEFT JOIN (
		SELECT PROM.LOCATION_MEMBER_KEY, 
			   PROM.PRODUCT_MEMBER_KEY,
			   PROM.START_DATE,
			   PROM.END_DATE
		FROM EDW_SPOKE..DIM_CAMPAIGN MASTER
			LEFT JOIN EDW_SPOKE..FACT_BPS_PROMOTION PROM ON MASTER.CAMPAIGN_KEY = PROM.CAMPAIGN_KEY	
	) AS EVENT ON ST.MEMBER_KEY = EVENT.LOCATION_MEMBER_KEY
		   AND PD.MEMBER_KEY = EVENT.PRODUCT_MEMBER_KEY
		   AND DT.DATE_VALUE BETWEEN EVENT.START_DATE AND EVENT.END_DATE	
	LEFT JOIN DBM_SANDBOX..CONSUMER_SENTIMENT CONSENT ON DT.MONTH_NUMBER_IN_CALENDAR_YEAR = EXTRACT(MONTH FROM CONSENT.DATE)
													 AND DT.CALENDAR_YEAR = EXTRACT(YEAR FROM CONSENT.DATE)
WHERE ST.CHANNEL_GROUP = 'RETAIL'
	AND DT.DATE_VALUE BETWEEN '2015-01-01' AND '2017-07-01'
	AND SD.RETURN_FLAG <> 'Y'
	AND SD.ACTUAL_SALE_FLAG = 'Y'
	AND PD.SKU_DISPLAY_NUMBER = '389648'
	AND ST.STORE_NUMBER IN ('001')
GROUP BY DT.DATE_VALUE, CONSENT.UMCSENT, ST.STORE_NUMBER, PD.SKU_DISPLAY_NUMBER
ORDER BY ST.STORE_NUMBER, PD.SKU_DISPLAY_NUMBER, DT.DATE_VALUE
