SELECT HIST.FISCAL_YEAR,
	   CASE
		   WHEN FUT.DIRFLG = 1 AND FUT.RETFLG = 1 THEN 'A. YES DIR/RET'
		   WHEN FUT.DIRFLG = 1 AND FUT.RETFLG = 0 THEN 'B. YES DIR ONLY'
		   WHEN FUT.DIRFLG = 0 AND FUT.RETFLG = 1 THEN 'C. YES RET ONLY'
		   ELSE 'D.NO'
	   END AS REBUYER,
	   SUM(CASE WHEN HIST.FREQ = 1 THEN 1 ELSE 0 END) AS FREQ_1X,
	   SUM(CASE WHEN HIST.FREQ > 1 THEN 1 ELSE 0 END) AS FREQ_2XPLUS,
	   SUM(1) AS TOTAL,
	   SUM(CASE WHEN HIST.DEMAND_SALES BETWEEN 0 AND 25 THEN 1 ELSE 0 END) AS SPEND_0_25,
	   SUM(CASE WHEN HIST.DEMAND_SALES BETWEEN 25.01 AND 50 THEN 1 ELSE 0 END) AS SPEND_26_50,
	   SUM(CASE WHEN HIST.DEMAND_SALES BETWEEN 50.01 AND 100 THEN 1 ELSE 0 END) AS SPEND_51_100,
	   SUM(CASE WHEN HIST.DEMAND_SALES BETWEEN 100.01 AND 250 THEN 1 ELSE 0 END) AS SPEND_101_250,
	   SUM(CASE WHEN HIST.DEMAND_SALES > 250 THEN 1 ELSE 0 END) AS SPEND_251_PLUS,
	   SUM(HIST.D100) AS D100BUYERS,
	   SUM(HIST.D151) AS D151BUYERS,
	   SUM(HIST.D175) AS D175BUYERS,
	   SUM(HIST.D200) AS D200BUYERS,
	   SUM(HIST.D300) AS D300BUYERS,
	   SUM(HIST.D350) AS D350BUYERS,
	   SUM(HIST.D400) AS D400BUYERS,
	   SUM(HIST.D450) AS D450BUYERS,
	   SUM(HIST.D475) AS D475BUYERS,
	   SUM(HIST.D500) AS D500BUYERS,
	   SUM(HIST.D600) AS D600BUYERS,
	   SUM(HIST.D650) AS D650BUYERS,
	   SUM(HIST.D675) AS D675BUYERS,
	   SUM(HIST.D700) AS D700BUYERS,
	   SUM(HIST.D800) AS D800BUYERS,
	   SUM(HIST.D850) AS D850BUYERS,
	   SUM(HIST.D875) AS D875BUYERS,
	   SUM(HIST.D999) AS D999BUYERS,
	   sum(HIST.BrandedYes) AS BrandedYes,
	   sum(hist.BrandedNo) AS BrandedNo
FROM (
	SELECT DT.FISCAL_YEAR,
		   SH.CUSTOMER_MEMBER_KEY,
		   COUNT(DISTINCT SH.INBOUND_INTERACTION_KEY) AS FREQ,
		   SUM(SD.DEMAND_SALES_PRICE) AS DEMAND_SALES,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0100' THEN 1 ELSE 0 END) AS D100,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0151' THEN 1 ELSE 0 END) AS D151,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0175' THEN 1 ELSE 0 END) AS D175,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0200' THEN 1 ELSE 0 END) AS D200,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0300' THEN 1 ELSE 0 END) AS D300,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0350' THEN 1 ELSE 0 END) AS D350,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0400' THEN 1 ELSE 0 END) AS D400,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0450' THEN 1 ELSE 0 END) AS D450,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0475' THEN 1 ELSE 0 END) AS D475,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0500' THEN 1 ELSE 0 END) AS D500,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0600' THEN 1 ELSE 0 END) AS D600,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0650' THEN 1 ELSE 0 END) AS D650,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0675' THEN 1 ELSE 0 END) AS D675,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0700' THEN 1 ELSE 0 END) AS D700,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0800' THEN 1 ELSE 0 END) AS D800,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0850' THEN 1 ELSE 0 END) AS D850,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0875' THEN 1 ELSE 0 END) AS D875,
		   MAX(CASE WHEN PROD.DEPARTMENT_DISPLAY_NUMBER = '0999' THEN 1 ELSE 0 END) AS D999,
		   MAX(CASE WHEN PROD.SKU_ITEM_LABEL_CODE IN ('B','R') THEN 1 ELSE 0 END) AS BrandedYes,
		   MAX(CASE WHEN PROD.SKU_ITEM_LABEL_CODE NOT IN ('B','R') THEN 1 ELSE 0 END) AS BrandedNo
		   		   	   
	FROM EDW_SPOKE..FACT_BPS_SALES_HEADER SH 
	 JOIN EDW_SPOKE..FACT_BPS_SALES_DETAIL SD ON SH.INBOUND_INTERACTION_KEY = SD.SH_INBOUND_INTERACTION_KEY
	 JOIN EDW_SPOKE..DIM_CHANNEL CH ON SD.CHANNEL_KEY = CH.CHANNEL_KEY
	 JOIN EDW_SPOKE..DIM_DATE DT ON SH.TRANSACTION_DATE_KEY = DT.DATE_KEY
	 JOIN EDW_SPOKE..DIM_PRODUCT_BPS PROD ON SD.INVENTORY_PRODUCT_MEMBER_KEY = PROD.MEMBER_KEY
	WHERE (CH.CHANNEL_GROUP = 'DIRECT' AND SH.ORDER_TYPE <> 'R' AND SH.ORDER_NUMBER IS NOT NULL)
		  --((CH.CHANNEL_GROUP = 'DIRECT' AND SH.ORDER_TYPE <> 'R' AND SH.ORDER_NUMBER IS NOT NULL)
	      --OR
	      --(CH.CHANNEL_GROUP = 'RETAIL' AND SD.BPS_MARKDOWN_DESC <> 'RETURN'))
	      AND DT.FISCAL_YEAR BETWEEN 2009 AND (SELECT FISCAL_YEAR-1 FROM EDW_SPOKE..DIM_DATE WHERE DATE_VALUE = CURRENT_DATE)
	GROUP BY DT.FISCAL_YEAR, SH.CUSTOMER_MEMBER_KEY
) AS HIST
LEFT JOIN (
	SELECT DT.FISCAL_YEAR,
		   SH.CUSTOMER_MEMBER_KEY,
		   MAX(CASE WHEN CH.CHANNEL_GROUP = 'DIRECT' THEN 1 ELSE 0 END) AS DIRFLG,
		   MAX(CASE WHEN CH.CHANNEL_GROUP = 'RETAIL' THEN 1 ELSE 0 END) AS RETFLG	   	   
	FROM EDW_SPOKE..FACT_BPS_SALES_HEADER SH 
	 JOIN EDW_SPOKE..FACT_BPS_SALES_DETAIL SD ON SH.INBOUND_INTERACTION_KEY = SD.SH_INBOUND_INTERACTION_KEY
	 JOIN EDW_SPOKE..DIM_CHANNEL CH ON SD.CHANNEL_KEY = CH.CHANNEL_KEY
	 JOIN EDW_SPOKE..DIM_DATE DT ON SH.TRANSACTION_DATE_KEY = DT.DATE_KEY
	WHERE ((CH.CHANNEL_GROUP = 'DIRECT' AND SH.ORDER_TYPE <> 'R' AND SH.ORDER_NUMBER IS NOT NULL)
	      OR
	      (CH.CHANNEL_GROUP = 'RETAIL' AND SD.BPS_MARKDOWN_DESC <> 'RETURN'))
	      AND DT.FISCAL_YEAR >= 2009
	      AND DT.FISCAL_PERIOD <= (SELECT CASE WHEN FISCAL_PERIOD = 1 THEN 12 ELSE FISCAL_PERIOD-1 END FROM EDW_SPOKE..DIM_DATE WHERE DATE_VALUE = CURRENT_DATE)
	GROUP BY DT.FISCAL_YEAR, SH.CUSTOMER_MEMBER_KEY
) AS FUT ON HIST.CUSTOMER_MEMBER_KEY = FUT.CUSTOMER_MEMBER_KEY AND HIST.FISCAL_YEAR + 1 = FUT.FISCAL_YEAR

GROUP BY HIST.FISCAL_YEAR, REBUYER
ORDER BY HIST.FISCAL_YEAR DESC, REBUYER